server:
  port: ${PORT:8080}
spring:
  application:
    name: jom-healthy
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-jomhealthy-jomhealthy.b.aivencloud.com:12100/jomhealthy?useSSL=true&verifyServerCertificate=false&serverTimezone=Asia/Kuala_Lumpur&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: false
  profiles:
    active: dev
