server:
  port: ${PORT:8080}
spring:
  application:
    name: jom-healthy
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 💡 注意这里改成了 localhost 和 3306 端口，关闭了 SSL
    url: jdbc:mysql://localhost:3306/jomhealthy_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Kuala_Lumpur&useSSL=false
    # 💡 纯文本，不要加 ${}
    username: root
    password: 196921
  thymeleaf:
    cache: false
  profiles:
    active: dev